// Copies the MezoRouteExecutor ABI from the Foundry build into a typed module.
// Re-run after any contract change: `cd contracts && forge build`, then `npm run sync-abi` in web/.
import { readFileSync, writeFileSync } from "node:fs";

const source = new URL("../../contracts/out/MezoRouteExecutor.sol/MezoRouteExecutor.json", import.meta.url);
const target = new URL("../src/lib/abi/mezoRouteExecutor.ts", import.meta.url);
const { abi } = JSON.parse(readFileSync(source, "utf8"));
writeFileSync(
  target,
  `// Generated by scripts/sync-abi.mjs from contracts/out. Do not edit.\nexport const mezoRouteExecutorAbi = ${JSON.stringify(abi, null, 2)} as const;\n`,
);
console.log(`sync-abi: wrote ${abi.length} ABI entries`);
