// Copies the MezoRouteExecutor ABI and the Tigris Router/Pool custom errors from the Foundry build
// into typed modules. Re-run after any contract change: `cd contracts && forge build`, then
// `npm run sync-abi` in web/.
import { readFileSync, writeFileSync } from "node:fs";

function readAbi(contract) {
  const source = new URL(`../../contracts/out/${contract}.sol/${contract}.json`, import.meta.url);
  return JSON.parse(readFileSync(source, "utf8")).abi;
}

function writeModule(file, exportName, abi) {
  const target = new URL(`../src/lib/abi/${file}`, import.meta.url);
  writeFileSync(
    target,
    `// Generated by scripts/sync-abi.mjs from contracts/out. Do not edit.\nexport const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;\n`,
  );
  console.log(`sync-abi: wrote ${abi.length} ABI entries to ${file}`);
}

/** Custom errors only, one per signature (Router and Pool share some), sorted for a stable file. */
function uniqueErrors(abi) {
  const bySignature = new Map();
  for (const item of abi) {
    if (item.type !== "error") continue;
    bySignature.set(`${item.name}(${item.inputs.map((input) => input.type).join(",")})`, item);
  }
  return [...bySignature.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([, item]) => item);
}

writeModule("mezoRouteExecutor.ts", "mezoRouteExecutorAbi", readAbi("MezoRouteExecutor"));
writeModule("tigrisErrors.ts", "tigrisErrorsAbi", uniqueErrors([...readAbi("Router"), ...readAbi("Pool")]));
