// Generated by scripts/sync-abi.mjs from contracts/out. Do not edit.
export const mezoRouteExecutorAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "musd_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "btc_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "router_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "factory_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "pool_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "borrowerOperationsSignatures_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "feeBps_",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "feeRecipient_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "maxMusdIn_",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "MAX_FEE_BPS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "borrowAndEnter",
    "inputs": [
      {
        "name": "b",
        "type": "tuple",
        "internalType": "struct IMezoRouteExecutor.Borrow",
        "components": [
          {
            "name": "amount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "upperHint",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "lowerHint",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "signature",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "deadline",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      },
      {
        "name": "musdPermit",
        "type": "tuple",
        "internalType": "struct IMezoRouteExecutor.Permit",
        "components": [
          {
            "name": "value",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "deadline",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "v",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "r",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "s",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct IMezoRouteExecutor.EnterParams",
        "components": [
          {
            "name": "musdIn",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "musdToSwap",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minBtcFromSwap",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minMusdAdded",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minBtcAdded",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minLpOut",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "deadline",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "recipient",
            "type": "address",
            "internalType": "address"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "liquidityOut",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "borrowerOperationsSignatures",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IBorrowerOperationsSignatures"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "btc",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IERC20"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "enter",
    "inputs": [
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct IMezoRouteExecutor.EnterParams",
        "components": [
          {
            "name": "musdIn",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "musdToSwap",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minBtcFromSwap",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minMusdAdded",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minBtcAdded",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minLpOut",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "deadline",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "recipient",
            "type": "address",
            "internalType": "address"
          }
        ]
      },
      {
        "name": "musdPermit",
        "type": "tuple",
        "internalType": "struct IMezoRouteExecutor.Permit",
        "components": [
          {
            "name": "value",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "deadline",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "v",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "r",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "s",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "liquidityOut",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "exit",
    "inputs": [
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct IMezoRouteExecutor.ExitParams",
        "components": [
          {
            "name": "liquidityIn",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minMusdRemoved",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minBtcRemoved",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minMusdFromSwap",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minMusdOut",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "deadline",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "recipient",
            "type": "address",
            "internalType": "address"
          }
        ]
      },
      {
        "name": "lpPermit",
        "type": "tuple",
        "internalType": "struct IMezoRouteExecutor.Permit",
        "components": [
          {
            "name": "value",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "deadline",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "v",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "r",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "s",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "musdOut",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "factory",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "feeBps",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "feeRecipient",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "maxMusdIn",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "musd",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IERC20"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pool",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IERC20"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "router",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract ITigrisRouter"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "Entered",
    "inputs": [
      {
        "name": "caller",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "recipient",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "musdBorrowed",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "musdIn",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "fee",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "musdSwapped",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "btcFromSwap",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "musdAdded",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "btcAdded",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "liquidityOut",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "musdRefund",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "btcRefund",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Exited",
    "inputs": [
      {
        "name": "caller",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "recipient",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "liquidityIn",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "musdRemoved",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "btcRemoved",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "musdFromSwap",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "musdOut",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "btcRefund",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AmountAboveCap",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BorrowAmountMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Expired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "FactoryMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "FeeTooHigh",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InsufficientFinalOutput",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InsufficientLiquidityOutput",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InsufficientSwapOutput",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidRecipient",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidSwapAmount",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotBorrower",
    "inputs": []
  },
  {
    "type": "error",
    "name": "PoolMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnexpectedBalanceDecrease",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroAmount",
    "inputs": []
  }
] as const;
