// Generated by scripts/sync-abi.mjs from contracts/out. Do not edit.
export const tigrisErrorsAbi = [
  {
    "type": "error",
    "name": "BelowMinimumK",
    "inputs": []
  },
  {
    "type": "error",
    "name": "DepositsNotEqual",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Expired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "FactoryAlreadySet",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InsufficientAmount",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InsufficientAmountA",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InsufficientAmountADesired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InsufficientAmountAOptimal",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InsufficientAmountB",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InsufficientAmountBDesired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InsufficientInputAmount",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InsufficientLiquidity",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InsufficientLiquidityBurned",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InsufficientLiquidityMinted",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InsufficientOutputAmount",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidPath",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidRouteA",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidRouteB",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidShortString",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidTo",
    "inputs": []
  },
  {
    "type": "error",
    "name": "IsPaused",
    "inputs": []
  },
  {
    "type": "error",
    "name": "K",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotDeployer",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotEmergencyCouncil",
    "inputs": []
  },
  {
    "type": "error",
    "name": "PoolDoesNotExist",
    "inputs": []
  },
  {
    "type": "error",
    "name": "PoolFactoryDoesNotExist",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SameAddresses",
    "inputs": []
  },
  {
    "type": "error",
    "name": "StringTooLong",
    "inputs": [
      {
        "name": "str",
        "type": "string",
        "internalType": "string"
      }
    ]
  },
  {
    "type": "error",
    "name": "VoterAlreadyInitialized",
    "inputs": []
  },
  {
    "type": "error",
    "name": "VoterNotInitialized",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  }
] as const;
